train_data_set : "srg"
num_layers : 5
JK : "last"
exp_name : "srg"
fold : 5
metric : "acc"
train_mode_test : False
num_epochs : 1000
num_rl_epochs : 1000

train_sample_size : 5000
eval_sample_size : 1000

# data related
data_trans : ["graph_data_k_fold_split", "add_replay_data"]
prepare_model : "prepare_no_feat_graph"
agent_eval : "cls"

# rl related
q_steps: 4
memory_capacity : 3000000
sync_rate : 1000
eps_last_frame : 100000
eps_first_frame: 50000
exp_steps : 4

loss : "ce"
loss_func : "classification_func"
eval_func : "classification_func"
eval_mode : "max"